### ISSUE TITLE
Page not loading on Safari 10.x

### ISSUE THREAD

**Issue by funkycoda** [Vizzuality/half-earth#137]
The regional and global pages doesn't seem to load on Safari 10.0.1. 

Page: https://half-earth.vizzuality.com/regional
Safari version: 10.0.1 (12602.2.14.0.7)
Error:
```js
TypeError: i is not a function. (In 'i("https://"+t+".carto.com/api/"+n+"/map?config="+encodeURIComponent(JSON.stringify(r)))', 'i' is undefined) — main.js:26611
```

**Comment by funkycoda** [comment]
Seems to work fine on Version 11.0 (11604.1.38.1.7)

**Comment by sorodrigo** [comment]
Please review changes

**Comment by guizar** [comment]
Hi @funkycoda, could you please test if this is still an issue on your end? thanks

**Comment by funkycoda** [comment]
Tested this yesterday and it looks like it still doesn't work. I'll get access to the machine today, so I'll send a bit more detailed error message

**Comment by guizar** [comment]
Hi Ajay, thanks for the update. We'll keep on looking into this issue

**Comment by funkycoda** [comment]
Still looks like the same error (assuming the site is still: https://half-earth.vizzuality.com/regional )

```js
TypeError: i is not a function. (In 'i("https://"+t+".carto.com/api/"+n+"/map?config="+encodeURIComponent(JSON.stringify(r)))', 'i' is undefined)

f — main.js:21495
```
